[[headers]]
  # Apply to all routes
  for = "/*"

  # Security Headers
  [headers.values]
  Content-Security-Policy = "default-src 'self'"
  Feature-Policy = "* none"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = ""nosniff" always"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"